export const inventoryCardData = [
    {
        title: "Total Inventory",
        value: 246,
        unit: "vehicles",
        icon: "/cardicons/total-inventory.svg",
        trendIcon: "/cardicons/arrow-up.svg",
        trendValue: "8%",
        trendText: "from last week",
        trendColor: undefined,
        subtitle: undefined,
        iconColor: undefined,
        valueColor: undefined,
    },
    {
        title: "Vehicles Added",
        value: 42,
        unit: "this week",
        icon: "/cardicons/vehiclesAdded.svg",
        trendIcon: "/cardicons/arrow-up.svg",
        trendValue: "12%",
        trendText: "from previous week",
        trendColor: undefined,
        subtitle: undefined,
        iconColor: undefined,
        valueColor: undefined,
    },
    {
        title: "Vehicles Sold",
        value: 27,
        unit: "this week",
        icon: "/cardicons/vehicle-sold.svg",
        trendIcon: "/cardicons/arrow-down.svg",
        trendValue: "3%",
        trendText: "from previous week",
        trendColor: "#F04438",
        subtitle: undefined,
        iconColor: "#E3A7B5",
        valueColor: undefined,
    },
];

export const inventoryLevelData = [
  { week: "W1", value: 225 },
  { week: "W2", value: 230 },
  { week: "W3", value: 228 },
  { week: "W4", value: 231 },
  { week: "W5", value: 233 },
  { week: "W6", value: 232 },
  { week: "W7", value: 235 },
  { week: "W8", value: 235 },
]

export const inventoryListTableData = [
    {
        stock: "RC4522",
        make: "Renault Clio",
        variant: "Evolution Tce 90",
        type: "Hatchback, Red",
        price: "€19,450",
        days: "28 days",
        status: "Active",
    },
    {
        stock: "PC3078",
        make: "Peugeot 308",
        variant: "Allura PureTech 130",
        type: "Hatchback, Blue",
        price: "€24,750",
        days: "46 days",
        status: "Aging Stock",
    },
    {
        stock: "CA5642",
        make: "Citroën C4",
        variant: "Shine BlueHDi 130",
        type: "SUV, Orange",
        price: "€22,890",
        days: "12 days",
        status: "Active",
    },
    {
        stock: "RA7721",
        make: "Renault Arkana",
        variant: "RS Line E-Tech 145",
        type: "Hatchback, White",
        price: "€15,000",
        days: "8 days",
        status: "Active",
    },
];
