export const inventoryCardData = [
    {
        title: "Total Inventory",
        value: 246,
        unit: "vehicles",
        icon: "/cardicons/total-inventory.svg",
        trendIcon: "/cardicons/arrow-up.svg",
        trendValue: "8%",
        trendText: "from last week",
        trendColor: undefined,
        subtitle: undefined,
        iconColor: undefined,
        valueColor: undefined,
    },
    {
        title: "Vehicles Added",
        value: 42,
        unit: "this week",
        icon: "/cardicons/vehiclesAdded.svg",
        trendIcon: "/cardicons/arrow-up.svg",
        trendValue: "12%",
        trendText: "from previous week",
        trendColor: undefined,
        subtitle: undefined,
        iconColor: undefined,
        valueColor: undefined,
    },
    {
        title: "Vehicles Sold",
        value: 27,
        unit: "this week",
        icon: "/cardicons/vehicle-sold.svg",
        trendIcon: "/cardicons/arrow-down.svg",
        trendValue: "3%",
        trendText: "from previous week",
        trendColor: "#F04438",
        subtitle: undefined,
        iconColor: "#E3A7B5",
        valueColor: undefined,
    },
];

export const inventoryLevelData = [
  { week: "W1", value: 225 },
  { week: "W2", value: 230 },
  { week: "W3", value: 228 },
  { week: "W4", value: 231 },
  { week: "W5", value: 233 },
  { week: "W6", value: 232 },
  { week: "W7", value: 235 },
  { week: "W8", value: 235 },
]