export const pricingIntelligenceCardData = [
    {
        title: "Price-to-Market Index",
        value: "1.03",
        unit: "overall",
        icon: "/cardicons/demandCoverage-icon.svg",
        trendIcon: "/cardicons/arrow-down.svg",
        trendValue: "0.01%",
        trendText: "from last month",
        trendColor: "#E00034",
        subtitle: undefined,
        iconColor: "#E3A7B5",
        valueColor: undefined,
    },
    {
        title: "Overpriced Vehicles",
        value: 14,
        unit: "vehicles",
        icon: "/cardicons/overPriced-icon.svg",
        trendIcon: "/cardicons/arrow-down.svg",
        trendValue: "3%",
        trendText: "from last month",
        trendColor: "#E00034",
        subtitle: undefined,
        iconColor: "#E00034",
        valueColor: undefined,
    },
    {
        title: "Underpriced Vehicles",
        value: 8,
        unit: "vehicles",
        icon: "/cardicons/underPriced-icon.svg",
        trendIcon: "/cardicons/arrow-up.svg",
        trendValue: "2%",
        trendText: "from last month",
        trendColor: undefined,
        subtitle: undefined,
        iconColor: undefined,
        valueColor: undefined,
    },
    {
        title: "Price Adjustments Needed",
        value: 22,
        unit: "vehicles",
        icon: "/cardicons/priceAdjustment-icon.svg",
        trendIcon: "/cardicons/arrow-down.svg",
        trendValue: "5%",
        trendText: "from last month",
        trendColor: "#E00034",
        subtitle: undefined,
        iconColor: "#E3A7B5",
        valueColor: undefined,
    },
];


export const regionalAveragePriceGraphData = [
    { "model": "Peugeot 2008", "searchVolume": 18, "inventory": 15 },
    { "model": "Renault Arkana", "searchVolume": 25, "inventory": 20 },
    { "model": "C5 Aircross", "searchVolume": 13, "inventory": 8 },
    { "model": "VW ID 4", "searchVolume": 29, "inventory": 27 },
    { "model": "Peugeot 3008", "searchVolume": 20, "inventory": 18 },
    { "model": "Renault Clio", "searchVolume": 14, "inventory": 13 },
    { "model": "Peugeot 208", "searchVolume": 23, "inventory": 20 },
    { "model": "Citroën C3", "searchVolume": 26, "inventory": 24 },
    { "model": "R. Captur", "searchVolume": 27, "inventory": 25 },
    { "model": "Peugeot 308", "searchVolume": 19, "inventory": 16 }
]
export const pricingOutliersTableData = [
    {
        stock: "RC4522",
        make: "Renault Clio",
        variant: "Evolution Tce 90",
        yourPrice: "€19,450",
        regionalPrice: "€17,890",
        difference: "+8.7%",
        suggestedPrice: "€18,200",
    },
    {
        stock: "PC3078",
        make: "Peugeot 308",
        variant: "Allura PureTech 130",
        yourPrice: "€22,450",
        regionalPrice: "€24,750",
        difference: "+10.2%",
        suggestedPrice: "€22,990",
    },
    {
        stock: "CA5642",
        make: "Citroën C4",
        variant: "Shine BlueHDi 130",
        yourPrice: "€15,990",
        regionalPrice: "€17,450",
        difference: "-8.4% ",
        suggestedPrice: "€16,750",
    },
    {
        stock: "RA7721",
        make: "Renault Arkana",
        variant: "RS Line E-Tech 145",
        yourPrice: "€28,950",
        regionalPrice: "€27,100",
        difference: "+6.8%",
        suggestedPrice: "€27,500",
    },
];

